apiVersion: apps/v1
kind: Deployment
metadata:
  name: electronics-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: electronics-store
  template:
    metadata:
      labels:
        app: electronics-store
    spec:
      containers:
      - name: electronics-store
        image: electronics-store:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: electronics-store-service
spec:
  type: NodePort
  selector:
    app: electronics-store
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30002
