apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pet-store
  template:
    metadata:
      labels:
        app: pet-store
    spec:
      containers:
      - name: pet-store
        image: pet-store:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: pet-store-service
spec:
  type: NodePort
  selector:
    app: pet-store
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30003
