apiVersion: apps/v1
kind: Deployment
metadata:
  name: es-mysql
  labels:
    app: es-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: es-mysql
  template:
    metadata:
      labels:
        app: es-mysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "password123"
            - name: MYSQL_USER
              value: "admin"
            - name: MYSQL_PASSWORD
              value: "password123"
            - name: MYSQL_DATABASE
              value: "electronics-store"
          ports:
            - containerPort: 3306
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
      # Optional: You may want to define persistent storage for MySQL data
      # volumes:
      #   - name: mysql-persistent-storage
      #     persistentVolumeClaim:
      #       claimName: mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: es-mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP # Change to NodePort or LoadBalancer if you want external access
