apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffee-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coffee-shop
  template:
    metadata:
      labels:
        app: coffee-shop
    spec:
      containers:
      - name: coffee-shop
        image: coffee-shop
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: coffee-shop-service
spec:
  type: NodePort
  selector:
    app: coffee-shop
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30005
